---
title: "Portfolio Quarto Website"
---

This is my Quarto website.

**AIM: To improve model validation, data processing, data visulation with the SECR package**

## Data
First section

## Data Processing
Second section

- 1
- 2
- 3

## Model Validation
::: {.callout-note}
A structured academic investigation into [topic].
:::

---

## Data Visualisation

::: {.grid}

::: {.g-col-6}
### Project 1
Short description of what you did.

[View more →](#)
:::

::: {.g-col-6}
### Project 2
Short description of another project.

[View more →](#)
:::

::: {.g-col-6}

---

## SECR Package
Spatially Explicit Capture Recapture

::: {.callout-note}
To access the function, first install SECR, install.packages("secr")
:::

Functions to estimate the density and size of a spatially distributed animal population sampled with an array of passive acoustic monitors (PAMs). Models incorporate distance-dependent detection are fitted by maximising the likelihood. Tools are also included for data manipulation and model selection.
Spatially explicit capture-recapture is a set of methods for studying marked animals distributed in space. Data consists from the location of detectors and their histories of marked animals. Models for population density and detection are defined in secr using symbolic formula notation. Density models
may include spatial or temporal trend, with predictors corresponding to time or behaviour. 